import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// The stylesheet is resolved by Next.js at build time.
// @ts-expect-error CSS side-effect imports are not typed by TypeScript.
import "@/app/globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Muhammad Zaeem - Front End Developer",
  description: "Generated by Muhammad Zaeem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>       
       <body className={spaceGrotesk.className}>{children}</body>
    </html>
  );
}
